name: Deploy Action to PRODUCTION
on:
  pull_request:
    branches:
      - main

jobs:
  run-on-prod-env:
    name: Run on PRODUCTION Environment
    runs-on: ubuntu-latest
    environment:
      name: PRODUCTION

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print Start Message
        run: echo "Starting deployment checks for PRODUCTION environment..."

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          app_location: "/"           
          output_location: "/"        
